# Generated by Django 4.2.4 on 2023-08-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_oderitem_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
